// Generated by CoffeeScript 1.6.2
(function() {
  var debug;

  debug = require("debug")("pause");

  module.exports = function(app) {
    var middleware, paused, reqs;

    paused = false;
    reqs = 0;
    middleware = function(req, res, next) {
      var end;

      if (paused) {
        debug("new request, refusing");
        res.setHeader("Connection", "close");
        return res.send(503);
      } else {
        reqs++;
        debug("#requests = " + reqs);
        end = res.end;
        res.end = function(chunk, encoding) {
          res.end = end;
          res.end(chunk, encoding);
          reqs--;
          debug("#requests = " + reqs);
          if (req === 0 && paused) {
            return app.emit("idle");
          }
        };
        return next();
      }
    };
    middleware.pause = function() {
      if (!paused) {
        paused = true;
        if (reqs === 0) {
          return process.nextTick(function() {
            return app != null ? app.emit("idle") : void 0;
          });
        }
      }
    };
    middleware.resume = function() {
      return paused = false;
    };
    app.pause = function() {
      return middleware.pause();
    };
    app.resume = function() {
      return middleware.resume();
    };
    return middleware;
  };

}).call(this);
